### ISSUE TITLE
Launch the app with default config

### ISSUE THREAD

**Issue by pegaltier** [Holo-Host/hp-admin#117]
I installed the app and I would like to try it with the mock dataset. I started the server and it works but then i get this error on the browser:

SchemaError.js:39 Uncaught Error: Query.holofuelUser defined in resolvers, but not in schema SchemaError	@	SchemaError.js:39

**Comment by jmday** [comment]
Hello @pegaltier . Thanks for raising awareness of this issue you encountered. We'll be sure to take a look! 

In case this doesn't get prioritized for quick response, please understand that we're not yet supporting any external users of Holo Hosting or our HP Admin app (but that will change by the end of the year as we support our early HoloPort owners!). Our current focus is our internal org Holo Hosting Network.

**Comment by peeech** [comment]
This issue is impossible to reproduce with current description. Closing as stale.
