### ISSUE TITLE
A flood of errors from websocket connection after page reload

### ISSUE THREAD

**Issue by peeech** [Holo-Host/hp-admin#230]
**Description**
HP Admin is trying to open multiple websocket connections to holoport, without providing authorization signature, therefore they are failing. This happens only after user is trying to access `holofuel` part of HP Admin UI BEFORE they log in.

**To Reproduce**
From blank browser tab try to access HP Admin at the url `https://myholoport.holohost.net/holofuel/`. This will redirect you to `https://myholoport.holohost.net/admin/login` and trigger a flood of network requests to `wss://myholoport.holohost.net/api/v1/ws/?X-Hpos-Admin-Signature=` with the 401 response code.

**Desired behavior**
Redirect to login page should not trigger multiple attempts to open wss connection.

**Why it happens?**
This issue is present because javascript does not keep track of websocket connections it's trying to open.

When the browser is trying to access `/holofuel/` endpoint the order of events is as follows:
- javascript is loaded
- javascript tries to open wss connection to holoport by sending `UPGRADE` GET request to holoport
- because user has not logged in yet there are no signing credentials present in the UI, therefore `X-Hpos-Admin-Signature` is empty
- holoport returns `401` to `UPGRADE` request because signature is not valid
- UI detects 401 and front-side redirects to login page
- websocket connection is persistent so after receiving `close` event it re-tries to open websocket connection with the same `UPGRADE` request

This last point results in reoccurring call to wss endpoint.

**Proposed fix**
websocket connection handler needs to keep track of websocket connections it is trying to open and keep it at 1. Also after 401 failure it should kill this connection to prevent it from retrying. Most likely changing wrapping function from async to synchronous would help.

**Comment by JettTech** [comment]
Resolved by PR #236 : simplest ws solution resolution.
