### ISSUE TITLE
Firefox Accept/Decline button presentation is slightly broken

### ISSUE THREAD

**Issue by Connoropolous** [Holo-Host/hp-admin#231]
As @JettTech knows, I've been doing some following along with PRs and work progress out of curiosity, and came across this issue while actually running the `develop` branch locally. I hesitated to log it, but why not?

It's a tiny detail, but very noticeable.

At `http://localhost:3100/holofuel/inbox`, Browser: Firefox
<img width="534" alt="Screen Shot 2020-03-29 at 10 28 12 AM" src="https://user-images.githubusercontent.com/1409121/77851679-6881c180-71a8-11ea-8681-f0e4933545e0.png">

**Comment by Connoropolous** [comment]
@JettTech I can open a PR for it, if you like...

**Comment by robbiecarlton** [comment]
@Connoropolous - currently the designs are mobile only, so when doing UI testing you should turn on browser simulation. We're moving to new responsive designs, but the current designs are ignoring desktop.

**Comment by robbiecarlton** [comment]
and @Connoropolous if you want to submit the fix, we'll merge it :D

**Comment by JettTech** [comment]
@Connoropolous - Your PR submissions are welcome! :100:   

Currently, our top priority is a smooth functional interaction and a clean mobile design/interface through which we can test the UX flow and overall experience with TestFuel.  ...and as @robbiecarlton pointed out, our desktop views/ responsive breakpoints are currently in the process of design. 

With this knowledge in mind, please feel free to contribute whenever you see fit. :rocket:

**Comment by SIR-R0B** [comment]
Well said @JettTech! :)

**Comment by Connoropolous** [comment]
all this info info about mobile first focus certainly explains what was confusing me about the layout (as was using it in normal desktop view)
