### ISSUE TITLE
Unable to nix-shell

### ISSUE THREAD

**Issue by willemolding** [Holo-Host/hp-admin#97]
Not sure if this is a problem with my setup but if I try to load up the nix shell by running `nix-shell` from the root I get
```
error: invalid regular expression '(^|.*/)\.\#[^/]*', at /nix/store/8vflrzd51a8ldpknf0c597y9q5vc21wz-source/rules.nix:38:26
```

Anyone else seen this?

**Comment by zo-el** [comment]
I haven't seen that issue. 
But I did update the nix-shell recently too. Could you try it out again?

**Comment by peeech** [comment]
Looks like this is not an issue anymore
